Repository Freshly/standard_view, pull requests merged in 2020-04, with the labels that each got.

#44 Release 0.1.8
  CHANGELOG.md
  Gemfile.lock
  lib/generators/model/model/model_generator.rb
  lib/standard_view/version.rb
  standard_view.gemspec
Labels: Release

#46 Version Bump
  Gemfile.lock
  standard_view.gemspec
Labels: Correction

#47 Release 0.1.9
  CHANGELOG.md
  Gemfile.lock
  lib/generators/model/model/model_generator.rb
  lib/standard_view/version.rb
  standard_view.gemspec
Labels: Release

#52 Release 0.1.11
  .generators
  .rakeTasks
  CHANGELOG.md
  Gemfile.lock
  app/helpers/standard_view/application_helper.rb
  app/views/application/_attribute_card_value.html.erb
  app/views/application/_attributes_card.html.erb
  config/locales/en.yml
  lib/standard_view/version.rb
Labels: Release

#53 fixing parent relationship
  CHANGELOG.md
  Gemfile.lock
  app/views/standard_view/_breadcrumbs.html.erb
  app/views/standard_view/_new.html.erb
  lib/standard_view/version.rb
Labels: Correction

#54 Release 0.1.12
  CHANGELOG.md
  Gemfile.lock
  app/views/standard_view/_breadcrumbs.html.erb
  app/views/standard_view/_new.html.erb
  lib/standard_view/version.rb
Labels: Release

#56 Release 0.1.13
  CHANGELOG.md
  Gemfile.lock
  lib/standard_view/version.rb
  standard_view.gemspec
Labels: Maintenance
